swagger: '2.0'
info:
  description:  Rest API doc
  version: '1.0.0'
  title:  Rest API documentation
  termsOfService: 'http://swagger.io/terms/'
  contact:
    email: hammami.nihed.123@gmail.com
host: localhost:3000
basePath: /api/v1
schemes:
- http
paths: {}
responses:
        '200':
          description: Success
          schema:
            $ref: 'swagger.yaml#/definitions/schemas/User'                
        '400':
          description: Bad request
          schema:
            $ref: '#/definitions/Error'
        '404':
          description: Not found
          schema:
            $ref: '#/definitions/Error'
definitions:
    Error:
      type: object
      properties:
        code:
          type: string
        message:
          type: string
      required:
        - code
        - message