swagger: '2.0'
info:
  description:  Rest API doc
  version: '1.0.0'
  title:  Rest API documentation
  termsOfService: 'http://swagger.io/terms/'
  contact:
    email: emnasaada3@gmail.com
host: localhost:3002
basePath: /api/v1
schemes:
- http
paths: {}
responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/User'                
        '400':
          description: Bad request
          schema:
            $ref: '#/definitions/Error'
        '404':
          description: Not found
          schema:
            $ref: '#/definitions/Error'
definitions:
    Error:
      type: object
      properties:
        code:
          type: string
        message:
          type: string
      required:
        - code
        - message
    User:
      properties:
      email:
        type: string
        description: email of user
      password:
        type: string
        description: password of the user
